spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hexagonal?currentSchema=post_example_db
    username: pg-users-db
    password: xZovSm5FUcmNMudwNe
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      connection-timeout: 50000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: db-conn-pool
      connection-test-query: select 1 from dual
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
