spring:
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  datasource:
    url: jdbc:ojp[localhost:1059,localhost:1060,localhost:1061]_postgresql://host.docker.internal:5432/hexagonal?currentSchema=post_example_db
#    url: jdbc:ojp[localhost:1059]_postgresql://host.docker.internal:5432/userdb
    username: pg-users-db
    password: xZovSm5FUcmNMudwNe
#    driver-class-name: org.openjproxy.jdbc.Driver
#    type: org.springframework.jdbc.datasource.SimpleDriverDataSource

ojp:
  loadaware:
    selection:
      enabled: true
  health:
    check:
      interval: 3600s
      threshold: 60s
      timeout: 1s
  redistribution:
    idleRebalanceFraction: 1.0
    maxClosePerRecovery: 100
  multinode:
    retryAttempts: -1
    retryDelayMs: 5000

logging:
  level:
    root: info
    org.openjproxy: debug