<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pawg.hexagonal</groupId>
        <artifactId>debezium-cdc</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>pawg.hexagonal.cdc</groupId>
    <artifactId>debezium-app</artifactId>

    <dependencies>
        <dependency>
            <groupId>pawg.hexagonal.cdc</groupId>
            <artifactId>debezium-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>pawg.hexagonal.cdc</groupId>
            <artifactId>debezium-out-adapter</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>pawg.hexagonal.cdc</groupId>
            <artifactId>debezium-in-adapter</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>pawg.hexagonal.cdc</groupId>
            <artifactId>debezium-in-port</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>