server:
  port: 8082

spring:
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  datasource:
    url: jdbc:ojp[localhost:1059(hexApp),localhost:1060(hexApp),localhost:1061(hexApp)]_mysql://host.docker.internal:3306/example?createDatabaseIfNotExist=true&sslMode=PREFERRED&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    url: jdbc:ojp[localhost:1059]_mysql://host.docker.internal:3306/example?createDatabaseIfNotExist=true&sslMode=PREFERRED&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: hexample
    password: hexample
#    driver-class-name: org.openjproxy.jdbc.Driver
#    type: org.springframework.jdbc.datasource.SimpleDriverDataSource

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        format_sql: true
        hbm2ddl:
          halt_on_error: true
    show-sql: true
    generate-ddl: true
    # Hibernate ddl auto (none, create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

hexApp:
  ojp:
    loadaware:
      selection:
        enabled: true
    health:
      check:
        interval: 3600s
        threshold: 60s
        timeout: 1s
    redistribution:
      idleRebalanceFraction: 1.0
      maxClosePerRecovery: 100
    multinode:
      retryAttempts: -1
      retryDelayMs: 5000
    connection:
      pool:
        maximumPoolSize: 33
        minimumIdle: 3
        idleTimeout: 300000
        maxLifetime: 900000
        connectionTimeout: 15000
        connectionTestQuery: SELECT 1
        leakDetectionThreshold: 60000

logging:
  level:
    root: info
    org.openjproxy: debug