server:
  port: 8081
  servlet:
    context-path: /cdc

# spring-doc
application:
  springdoc:
    title: Hexagonal API
    description: Hexagonal POC.
    version: @project.version@
springdoc:
  show-actuator: false

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring:
  profiles:
    include:
      - debezium
  datasource:
    url: jdbc:mysql://localhost:3306/cdc?createDatabaseIfNotExist=true&sslMode=PREFERRED&serverTimeZone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: react
    password: MysqL12!@
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 50000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: db-conn-pool
      connection-test-query: select 1 from dual
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: mysql
  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
    show-sql: false
    generate-ddl: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
    open-in-view: off
# Actuator setup
management:
  endpoints:
    web:
      base-path: /mgm
      exposure:
        include: health,beans,logs,env
      path-mapping:
        health: status
  server:
    port: 8070